### ISSUE TITLE
Meteor mail not sending despite setting MAIL_URL environment variable

### ISSUE THREAD

**Issue by rahuldagli** [yogiben/meteor-pretty-email#10]
I'm getting this error message in the terminal "Mail not sent; to enable sending, set the MAIL_URL environment variable." despite setting MAIL_URL environment variable. After this message the whole mail content html gets dumped in the terminal. I'm using 2 meteor packages for sending email: yogiben:pretty-emails and email with mailgun api service.

Here's the source code for the mail config and sending email:

    if Meteor.isServer
        Meteor.startup ->
            process.env.MAIL_URL = 'smtp://sandboxid.mailgun.org:mypassword@smtp.mailgun.org:587'
            return

        PrettyEmail.options = 
            from: 'primaryemail@gmail.com'

            siteName: 'Meteor Test'
            companyAddress: 'sdfsf, gdfg-df'
            companyName: 'Code to Create'
            companyUrl: 'http://example.com'

        Accounts.sendVerificationEmail ->
            Meteor.userId()

This file is kept inside Project_Directory/both/_config directory. I'm currently developing this app on local ubuntu server.

**Comment by mpowaga** [comment]
You have to set MAIL_URL from command line, e.g:

```
MAIL_URL=smtp://sandboxid.mailgun.org:mypassword@smtp.mailgun.org:587 meteor
```
