### ISSUE TITLE
Adding an email using auto form. 

### ISSUE THREAD

**Issue by rwatts3** [yogiben/meteor-pretty-email#12]
In my app I want to create a collection called emails for my client. How would I create a button that would send the email with my message to the client I've selected in the drop down for the email.  

Just like composing an email in gmail or inbox.

**Comment by mpowaga** [comment]
It doesn't seem to be related to pretty-email package. Might be better if you ask on stackoverflow.

**Comment by rwatts3** [comment]
Hmm, 
Interesting way to treat a follower. I won't bother, i'll go with another package thanks for the diligent time to look into this.

**Comment by mpowaga** [comment]
Didn't want to offend you in any way. Github issues are for reporting bugs or discussion about the project.  Your question is more general.
