### ISSUE TITLE
Has anyone been able to clone this package into their packages folder?

### ISSUE THREAD

**Issue by sferoze** [yogiben/meteor-pretty-email#24]
I want to edit this package to correct the issue of text not being aligned center, and also remove the subject from the very top which looks odd. 

I cloned this package into my packages folder and everything works locally. But when I try and deploy, it deploys find but my app breaks with the console error saying it cannot find the variables `OriginalHandleBars` and `ServiceConfiguration`

I have no idea why it works locally but not deployed. How can I edit this package, im stuck

**Comment by sferoze** [comment]
I was able to clone the package and finally get it working in my packages directory by editing package.js specifically `api.use('cmather:handlebars-server@2.0.0');` to `api.use('cmather:handlebars-server');`

Just removed the version number from cmather handlebars package

**Comment by skarborg** [comment]
Did you get to the bottom of this @sferoze ?

It works only sometimes for me...

**Comment by sferoze** [comment]
@scarbies yah I figured it out.

Edit package.js file and replace cmather:handlebars-server dependency with 

https://atmospherejs.com/astrocoders/handlebars-server

cmathers-handlebars-server does not work with newest meteor version

**Comment by skarborg** [comment]
Awesome thanks I will check it out. Ver 2.0.0 still seems to work for me with Meteor 1.4.2 though

**Comment by sferoze** [comment]
@scarbies I thought so too, but it works on and off. Sometimes it does not work. Its buggy. But when I switched to the astrocoders re-write of the package it worked all the time.
