### ISSUE TITLE
Defaults not working

### ISSUE THREAD

**Issue by advany** [yogiben/meteor-pretty-email#6]
Have the following code:

PrettyEmail.defaults.verifyEmail = {
  heading: "Bevestig uw emailadres",
}

Options work, style works... but defaults seems to be empty somehow?!

Getting the following error...

W20150129-01:22:31.852(0)? (STDERR) TypeError: Cannot set property 'verifyEmail' of undefined                                                            
W20150129-01:22:31.852(0)? (STDERR)     at app/server/email.js:20:34                                                                                     
W20150129-01:22:31.852(0)? (STDERR)     at app/server/email.js:45:3                                                                                      
W20150129-01:22:31.852(0)? (STDERR)     at /home/action/workspace/islamAgenda/.meteor/local/build/programs/server/boot.js:205:10                         
W20150129-01:22:31.852(0)? (STDERR)     at Array.forEach (native)                                                                                        
W20150129-01:22:31.852(0)? (STDERR)     at Function._.each._.forEach (/home/action/.parts/packages/meteor/1.0/packages/meteor-tool/.1.0.40.lnogu8++os.lin
ux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)                         
W20150129-01:22:31.853(0)? (STDERR)     at /home/action/workspace/islamAgenda/.meteor/local/build/programs/server/boot.js:116:5

**Comment by BraveKenny** [comment]
Yep, I get the same error so far.

**Comment by BraveKenny** [comment]
I think it's because the latest code on this repo hasn't been published in the package yet... I don't see the default fields in the source of my installed package. Any news on when this will come?

**Comment by oliversd** [comment]
Same problem here

**Comment by BraveKenny** [comment]
If you want to get it working you can add the current github version of the package instead of the outdated "atmospherejs" one, by cloning this repo inside your `packages` folder, rename it "pretty-email" (remove "meteor-"), and add it to your meteor project using:
`meteor add pretty-email`
This should work. (just make sure you removed the outdated version first)
Of course you should then pay attention to evolutions on this package since updates won't be sent through that way. This is just a temporary solution.

**Comment by mpowaga** [comment]
Make sure that you set pretty email defaults on server-side code. PrettyEmail variable is not exported to the client

**Comment by esteedqueen** [comment]
Upgrade to version 0.0.5 ` yogiben:pretty-email@=0.0.5 ` fixes this

**Comment by mpowaga** [comment]
Yep. Its fixed. Closing.
